#!/usr/bin/env python3
"""
gen_chain.py — MediaServer OCR chain generator
===============================================
Reads a YAML document-type definition and:
  1. Generates Lua scripts (filter, per-field compute_dynamic_region, draw overlay)
  2. Patches Kapish_debug.cfg  (Filter → Combine → DynRegion → Draw → Save → OCR)
  3. Patches Kapish.cfg        (Filter → Combine → DynRegion → OCR; no Draw/Save)

Usage:
  python3 tools/gen_chain.py tools/definitions/wa_dl.yaml
  python3 tools/gen_chain.py tools/definitions/wa_dl.yaml --dry-run
  python3 tools/gen_chain.py tools/definitions/wa_dl.yaml --force
  python3 tools/gen_chain.py --list
"""

import argparse
import re
import shutil
import sys
from datetime import datetime
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required.  Install with:  pip3 install pyyaml")


# ---------------------------------------------------------------------------
# Default path resolution  (relative to this script's location)
# ---------------------------------------------------------------------------

TOOLS_DIR  = Path(__file__).resolve().parent
PROJ_DIR   = TOOLS_DIR.parent
CONFIG_DIR = PROJ_DIR / "mediaserver" / "MediaServer_26.2.0_LINUX_X86_64" / "configurations"
LUA_DIR    = CONFIG_DIR / "lua"
DEBUG_CFG  = CONFIG_DIR / "Kapish_debug.cfg"
PLAIN_CFG  = CONFIG_DIR / "Kapish.cfg"


# ===========================================================================
#  Lua generation
# ===========================================================================

def lua_filter(identifier: str) -> str:
    """Generate filter_<id_lower>.lua — pred() that matches one identifier."""
    id_low = identifier.lower()
    return (
        f"-- filter_{id_low}.lua\n"
        f"-- Auto-generated by gen_chain.py.  Edit the YAML and regenerate.\n"
        f"function pred(rec)\n"
        f"    local obj = rec.ObjectRecognitionResult or rec.ObjectRecognitionResultAndImage\n"
        f"    if not obj then\n"
        f'        log("filter_{id_low}: no ObjectRecognitionResult, skipping")\n'
        f"        return false\n"
        f"    end\n"
        f'    local ident = obj.identity and obj.identity.identifier or obj.name or "unknown"\n'
        f'    log("filter_{id_low}: identifier=\'" .. tostring(ident) .. "\'")\n'
        f'    local matched = ident == "{identifier}"\n'
        f'    if matched then\n'
        f'        log("filter_{id_low}: PASSED ({identifier})")\n'
        f'    else\n'
        f'        log("filter_{id_low}: REJECTED")\n'
        f'    end\n'
        f"    return matched\n"
        f"end\n"
    )


def lua_compute(identifier: str, field: dict, card: dict) -> str:
    """Generate compute_dynamic_region_<id>_<field_lower>.lua — rectangle() function."""
    id_low  = identifier.lower()
    fname   = field["name"]
    f_low   = fname.lower()
    desc    = field.get("description", fname)
    roi     = field["roi"]

    lw_f  = float(card.get("width_factor",       1.0))
    lh_f  = float(card.get("height_factor",      1.0))
    l_off = float(card.get("left_offset_factor", 0.0))
    t_off = float(card.get("top_offset_factor",  0.0))

    # Format floats without unnecessary trailing zeros
    def fmt(v):
        return f"{v:g}"

    if lw_f == 1.0 and lh_f == 1.0 and l_off == 0.0 and t_off == 0.0:
        card_note = "    -- Model detects the full card; bounding box IS the card."
    else:
        card_note = (
            "    -- Model detects a partial region (e.g. a header banner).\n"
            "    -- card_estimation factors extrapolate to the full card dimensions.\n"
            "    -- Verify by checking the debug pre_ocr PNG after first test run."
        )

    lines = [
        f"-- compute_dynamic_region_{id_low}_{f_low}.lua",
        f"-- Auto-generated by gen_chain.py",
        f"-- OCR region for {identifier} / {fname}: {desc}",
        "",
        "function rectangle(r)",
        f'    log("=== {identifier} {fname} Rectangle ===")',
        "",
        "    local result = r.ObjectRecognitionResult",
        "                or r.ObjectRecognitionResultAndImage",
        "                or r.ObjectRecognitionResultAndSource",
        "    if not result or not result.boundary or not result.boundary.point then",
        '        log("ERROR: no boundary found")',
        "        return nil",
        "    end",
        "",
        '    local ident = result.identity and result.identity.identifier or "unknown"',
        f'    if ident ~= "{identifier}" then',
        f'        log("Not {identifier}, skipping: " .. tostring(ident))',
        "        return nil",
        "    end",
        "",
        "    local pts = result.boundary.point",
        "    local min_x, min_y =  1e9,  1e9",
        "    local max_x, max_y = -1e9, -1e9",
        "    for _, p in ipairs(pts) do",
        "        min_x = math.min(min_x, p.x);  max_x = math.max(max_x, p.x)",
        "        min_y = math.min(min_y, p.y);  max_y = math.max(max_y, p.y)",
        "    end",
        "    local lw = max_x - min_x",
        "    local lh = max_y - min_y",
        "",
        card_note,
        f"    local card_left   = min_x + lw * {fmt(l_off)}",
        f"    local card_top    = min_y + lh * {fmt(t_off)}",
        f"    local card_width  = lw   * {fmt(lw_f)}",
        f"    local card_height = lh   * {fmt(lh_f)}",
        '    log(string.format("[Card] L:%.0f T:%.0f W:%.0f H:%.0f",',
        "        card_left, card_top, card_width, card_height))",
        "",
        f"    -- === {fname} ROI ===",
        "    -- Fractions are relative to the full card bounding box.",
        "    -- TODO: tune after first test run — check the debug pre_ocr PNG.",
        "    local roi = {",
        f"        left   = math.floor(card_left + card_width  * {fmt(roi['left'])}),",
        f"        top    = math.floor(card_top  + card_height * {fmt(roi['top'])}),",
        f"        width  = math.floor(card_width  * {fmt(roi['width'])}),",
        f"        height = math.floor(card_height * {fmt(roi['height'])}),",
        f'        label  = "{identifier}_{fname}"',
        "    }",
        "    if roi.left < 0 then roi.left = 0 end",
        "    if roi.top  < 0 then roi.top  = 0 end",
        f'    log(string.format("[ROI] {fname} -> L:%d T:%d W:%d H:%d",',
        "        roi.left, roi.top, roi.width, roi.height))",
        "    return { roi }",
        "end",
        "",
    ]
    return "\n".join(lines)


def lua_draw(identifier: str, draw_cfg: dict) -> str:
    """Generate draw/draw_<id_lower>.lua — draw() overlay for debug images."""
    id_low = identifier.lower()
    r1, g1, b1 = draw_cfg.get("roi_color",      [255, 165,   0])
    r2, g2, b2 = draw_cfg.get("boundary_color", [  0,   0, 160])
    # Darker variants for text backgrounds
    r1d, g1d, b1d = max(0, r1 - 50), max(0, g1 - 50), max(0, b1 - 50)
    r2d, g2d, b2d = max(0, r2 - 40), max(0, g2 - 40), max(0, b2 - 40)
    fallback = draw_cfg.get("label_fallback", (id_low.replace("_", "")[:3].upper() + "R"))

    lines = [
        f"-- draw_{id_low}.lua",
        f"-- Auto-generated by gen_chain.py",
        f"-- Debug draw overlay for {identifier}",
        "",
        "function draw(record)",
        "    -- 1. ROI rectangle",
        "    local rect = record.RectangleData or record.RegionData",
        "    if rect then",
        "        drawRectangle(",
        "            {left = math.floor(rect.left), top = math.floor(rect.top),",
        "             width = math.floor(rect.width), height = math.floor(rect.height)},",
        f"            4, rgb({r1}, {g1}, {b1}))",
        '        local lbl = (type(rect.label) == "string" and rect.label) or ' + f'"{fallback}"',
        "        drawText(lbl,",
        "            math.max(5, math.floor(rect.left)),",
        "            math.max(25, math.floor(rect.top) - 30),",
        f'            "DejaVuSans", 20, rgb(255, 255, 255), rgb({r1}, {g1}, {b1}))',
        "    end",
        "",
        "    -- 2. ObjectRecognition boundary polygon",
        "    local obj = record.ObjectRecognitionResultAndImage or record.ObjectRecognitionResult",
        "    if obj and obj.boundary and obj.boundary.point then",
        "        local pts = obj.boundary.point",
        "        for i = 1, #pts do",
        "            local p1 = pts[i]",
        "            local p2 = pts[(i % #pts) + 1]",
        "            drawLine(math.floor(p1.x), math.floor(p1.y),",
        "                     math.floor(p2.x), math.floor(p2.y),",
        f"                     2, rgb({r2}, {g2}, {b2}))",
        "        end",
        '        local ident = (obj.identity and obj.identity.identifier) or obj.name or '
        f'"{identifier}"',
        "        local conf  = (obj.identity and obj.identity.confidence) or 0",
        '        drawText(string.format("%s %.0f%%", ident, conf),',
        "            math.max(5, math.floor(pts[1].x)),",
        "            math.max(25, math.floor(pts[1].y) - 30),",
        f'            "DejaVuSans", 20, rgb(255, 255, 255), rgb({r2d}, {g2d}, {b2d}))',
        "    end",
        "",
        "    -- 3. OCR result overlay",
        "    if record.OCRResult and rect then",
        '        drawText("OCR: " .. (record.OCRResult.text or ""),',
        "            math.max(5, math.floor(rect.left)),",
        "            math.max(25, math.floor(rect.top + rect.height + 5)),",
        f'            "DejaVuSans", 20, rgb(255, 255, 255), rgb({r1d}, {g1d}, {b1d}))',
        "    end",
        "end",
        "",
    ]
    return "\n".join(lines)


# ===========================================================================
#  CFG helpers
# ===========================================================================

def get_session_engines(text: str) -> list:
    """Return the ordered list of engine names from the [Session] block."""
    m = re.search(r'\[Session\][^\[]*', text, re.DOTALL)
    if not m:
        return []
    return re.findall(r'Engine\d+\s*=\s*(\S+)', m.group())


def patch_session(text: str, new_names: list, before: str = "CombineOCRResults") -> str:
    """
    Insert new_names before `before` in the [Session] engine list and renumber all.
    The [Session] block must contain only Engine<N> = <Name> lines (no interspersed comments).
    """
    def _replace(m):
        existing = re.findall(r'Engine\d+\s*=\s*(\S+)', m.group())
        if before not in existing:
            return m.group()  # nothing to do
        idx = existing.index(before)
        merged = existing[:idx] + new_names + existing[idx:]
        lines = "\n".join(f"Engine{i:<2} = {n}" for i, n in enumerate(merged))
        return "[Session]\n" + lines + "\n"

    result = re.sub(
        r'\[Session\]\s*\n(?:[ \t]*Engine\d+[ \t]*=[ \t]*\S+[ \t]*\n)+',
        _replace,
        text,
    )
    if result == text:
        raise ValueError(
            f"Session block not found or '{before}' not in engine list.\n"
            "Ensure the [Session] section contains only Engine<N> = <Name> lines."
        )
    return result


def insert_stanzas_before(text: str, stanzas: str, anchor: str = "CombineOCRResults") -> str:
    """Insert stanza block immediately before the [<anchor>] section."""
    marker = f"\n[{anchor}]"
    idx = text.find(marker)
    if idx == -1:
        raise ValueError(f"[{anchor}] not found in cfg file")
    return text[:idx] + "\n" + stanzas.rstrip("\n") + text[idx:]


def add_combine_inputs(text: str, new_results: list) -> str:
    """
    Append InputN lines to [CombineOCRResults], inserting before its LuaScript= line.
    """
    combine_pos = text.find("\n[CombineOCRResults]")
    if combine_pos == -1:
        raise ValueError("[CombineOCRResults] not found in cfg file")
    luascript_pos = text.find("LuaScript", combine_pos)
    if luascript_pos == -1:
        raise ValueError("LuaScript= not found inside [CombineOCRResults]")
    block = text[combine_pos:luascript_pos]
    existing_nums = [int(x) for x in re.findall(r'Input(\d+)', block)]
    next_n = (max(existing_nums) + 1) if existing_nums else 0
    new_lines = "".join(f"Input{next_n + i} = {r}\n" for i, r in enumerate(new_results))
    return text[:luascript_pos] + new_lines + text[luascript_pos:]


# ===========================================================================
#  Stanza builders
# ===========================================================================

def _ocr_block(ocr: dict) -> str:
    """Build the per-OCR-engine settings lines from an ocr dict."""
    parts = [f"Languages = {ocr.get('languages', 'en')}"]
    if "character_types" in ocr:
        parts.append(f"CharacterTypes = {ocr['character_types']}")
    if "word_reject_threshold" in ocr:
        parts.append(f"WordRejectThreshold = {ocr['word_reject_threshold']}")
    if "ocr_mode" in ocr:
        parts.append(f"OCRMode = {ocr['ocr_mode']}")
    if ocr.get("process_text_elements"):
        parts.append("ProcessTextElements = True")
    return "\n".join(parts)


def build_stanzas(identifier: str, fields: list, id_low: str, debug: bool) -> str:
    """
    Return the cfg stanza block for all engines in the chain.
    debug=True adds Draw + Save engines; debug=False omits them.
    """
    parts = []

    parts.append(
        f"[Filter_{identifier}]\n"
        f"Type = filter\n"
        f"Input = ObjectRecognition.Result\n"
        f"LuaScript = filters/filter_{id_low}.lua\n"
    )
    parts.append(
        f"[Combine_{identifier}]\n"
        f"Type = combine\n"
        f"Input0 = RotateTask.Output\n"
        f"Input1 = Filter_{identifier}.Output\n"
    )

    for f in fields:
        fname = f["name"]
        f_low = fname.lower()
        ocr   = f.get("ocr", {})
        stem  = f"{id_low}_{f_low}"

        parts.append(
            f"[DynamicRegion_{identifier}_{fname}]\n"
            f"Type = setrectangle\n"
            f"Input = Combine_{identifier}.Output\n"
            f"LuaScript = compute_dynamic_region_{id_low}_{f_low}.lua\n"
        )

        if debug:
            parts.append(
                f"[Draw_PreOCR_{identifier}_{fname}]\n"
                f"Type = draw\n"
                f"Input = DynamicRegion_{identifier}_{fname}.Output\n"
                f"LuaScript = draw/draw_{id_low}.lua\n"
            )
            parts.append(
                f"[SavePreOCR_{identifier}_{fname}]\n"
                f"Type = imageencoder\n"
                f"ImageInput = Draw_PreOCR_{identifier}_{fname}.Output\n"
                f"OutputPath = output/debug/%source.filename.stem%_{stem}_pre_ocr.png\n"
            )
            ocr_input = f"Draw_PreOCR_{identifier}_{fname}.Output"
        else:
            ocr_input = f"DynamicRegion_{identifier}_{fname}.Output"

        parts.append(
            f"[OCR_{identifier}_{fname}]\n"
            f"Type = OCR\n"
            f"Input = {ocr_input}\n"
            f"Region = Input\n"
            f"{_ocr_block(ocr)}\n"
        )

    return "\n".join(parts)


def session_engine_names(identifier: str, fields: list, debug: bool) -> list:
    """Return the ordered engine names that go into [Session] for this chain."""
    names = [f"Filter_{identifier}", f"Combine_{identifier}"]
    for f in fields:
        fname = f["name"]
        names.append(f"DynamicRegion_{identifier}_{fname}")
        if debug:
            names.append(f"Draw_PreOCR_{identifier}_{fname}")
            names.append(f"SavePreOCR_{identifier}_{fname}")
        names.append(f"OCR_{identifier}_{fname}")
    return names


# ===========================================================================
#  Chain builder
# ===========================================================================

class ChainBuilder:
    def __init__(self, defn: dict, config_dir: Path, dry_run: bool, force: bool):
        self.defn       = defn
        self.config_dir = config_dir
        self.lua_dir    = config_dir / "lua"
        self.dry_run    = dry_run
        self.force      = force

        self.identifier = defn["identifier"]
        self.id_low     = self.identifier.lower()
        self.fields     = defn.get("fields", [])
        self.card       = defn.get("card_estimation", {})
        self.draw_cfg   = defn.get("draw", {})

    # -------------------------------------------------------------------------

    def _rel(self, path: Path) -> str:
        """Return a display-friendly relative path."""
        try:
            return str(path.relative_to(PROJ_DIR))
        except ValueError:
            return str(path)

    def _write_lua(self, path: Path, content: str):
        tag = "[DRY-RUN] " if self.dry_run else ""
        if path.exists() and not self.force:
            print(f"  SKIP (exists)   {self._rel(path)}")
            return
        if self.dry_run:
            print(f"  {tag}WRITE       {self._rel(path)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"  WROTE           {self._rel(path)}")

    def _patch_cfg(self, cfg_path: Path, debug: bool):
        label = cfg_path.name
        if not cfg_path.exists():
            print(f"  SKIP (not found)  {label}")
            return

        text = cfg_path.read_text(encoding="utf-8")

        # Guard against duplicates
        if re.search(rf'Engine\d+\s*=\s*Filter_{re.escape(self.identifier)}\b', text):
            print(f"  SKIP (already present)  {label}  →  Filter_{self.identifier} exists")
            return

        identifier = self.identifier
        id_low     = self.id_low
        fields     = self.fields

        try:
            text = patch_session(text, session_engine_names(identifier, fields, debug))
            text = insert_stanzas_before(text, build_stanzas(identifier, fields, id_low, debug))
            ocr_results = [f"OCR_{identifier}_{f['name']}.Result" for f in fields]
            text = add_combine_inputs(text, ocr_results)
        except ValueError as exc:
            print(f"  ERROR  {label}: {exc}")
            return

        if self.dry_run:
            print(f"  [DRY-RUN] PATCH   {label}")
        else:
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            backup = cfg_path.with_suffix(f".{ts}.bak")
            shutil.copy2(cfg_path, backup)
            print(f"  BACKUP            {self._rel(backup)}")
            cfg_path.write_text(text, encoding="utf-8")
            print(f"  PATCHED           {label}")

    # -------------------------------------------------------------------------

    def run(self):
        identifier = self.identifier
        id_low     = self.id_low
        fields     = self.fields

        print(f"\n{'='*62}")
        print(f"  Chain: {identifier}  |  Fields: {[f['name'] for f in fields]}")
        print(f"  Dry-run: {self.dry_run}  |  Force overwrite: {self.force}")
        print(f"{'='*62}\n")

        # -- Lua files ---------------------------------------------------------
        print("Lua files:")

        self._write_lua(
            self.lua_dir / "filters" / f"filter_{id_low}.lua",
            lua_filter(identifier),
        )
        for f in fields:
            self._write_lua(
                self.lua_dir / f"compute_dynamic_region_{id_low}_{f['name'].lower()}.lua",
                lua_compute(identifier, f, self.card),
            )
        self._write_lua(
            self.lua_dir / "draw" / f"draw_{id_low}.lua",
            lua_draw(identifier, self.draw_cfg),
        )

        # -- CFG files ---------------------------------------------------------
        print("\nCFG files:")
        self._patch_cfg(self.config_dir / "Kapish_debug.cfg", debug=True)
        self._patch_cfg(self.config_dir / "Kapish.cfg",       debug=False)

        # -- Summary -----------------------------------------------------------
        print()
        if not self.dry_run:
            print("Next steps:")
            print(f"  1. Restart MediaServer and process a {identifier} sample image.")
            for f in fields:
                stem = f"{id_low}_{f['name'].lower()}"
                print(f"  2. Check  output/debug/*_{stem}_pre_ocr.png")
                print(f"     Tune   lua/compute_dynamic_region_{id_low}_{f['name'].lower()}.lua")
            print("     (adjust left/top/width/height fractions until the box is correct)")


# ===========================================================================
#  Validation
# ===========================================================================

REQUIRED_DEFINITION_KEYS = ("identifier", "card_estimation", "fields")
REQUIRED_FIELD_KEYS      = ("name", "roi")
REQUIRED_ROI_KEYS        = ("left", "top", "width", "height")


def validate(defn: dict, path: Path):
    for k in REQUIRED_DEFINITION_KEYS:
        if k not in defn:
            sys.exit(f"ERROR: Missing required key '{k}' in {path}")
    if not defn["fields"]:
        sys.exit(f"ERROR: 'fields' list is empty in {path}")
    for f in defn["fields"]:
        for k in REQUIRED_FIELD_KEYS:
            if k not in f:
                sys.exit(f"ERROR: Field entry missing '{k}': {f}  ({path})")
        for k in REQUIRED_ROI_KEYS:
            if k not in f["roi"]:
                sys.exit(f"ERROR: Field '{f['name']}' roi missing '{k}'  ({path})")
        for k in REQUIRED_ROI_KEYS:
            v = f["roi"][k]
            if not (0.0 <= float(v) <= 2.0):
                sys.exit(f"ERROR: Field '{f['name']}' roi.{k}={v} looks wrong (expect 0–1)  ({path})")


# ===========================================================================
#  CLI commands
# ===========================================================================

def cmd_list(config_dir: Path):
    cfg_path = config_dir / "Kapish_debug.cfg"
    if not cfg_path.exists():
        sys.exit(f"Not found: {cfg_path}")
    engines = get_session_engines(cfg_path.read_text(encoding="utf-8"))
    print(f"\nEngines currently in {cfg_path.name}:\n")
    for i, name in enumerate(engines):
        print(f"  Engine{i:<2} = {name}")
    print()


def cmd_generate(args):
    def_path = Path(args.definition)
    if not def_path.exists():
        sys.exit(f"Definition file not found: {def_path}")

    with open(def_path, encoding="utf-8") as fh:
        defn = yaml.safe_load(fh)

    validate(defn, def_path)

    config_dir = Path(args.config_dir) if args.config_dir else CONFIG_DIR

    ChainBuilder(
        defn=defn,
        config_dir=config_dir,
        dry_run=args.dry_run,
        force=args.force,
    ).run()


# ===========================================================================
#  Entry point
# ===========================================================================

def main():
    parser = argparse.ArgumentParser(
        prog="gen_chain.py",
        description="Generate a MediaServer OCR extraction chain from a YAML definition.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python3 tools/gen_chain.py tools/definitions/wa_dl.yaml\n"
            "  python3 tools/gen_chain.py tools/definitions/wa_dl.yaml --dry-run\n"
            "  python3 tools/gen_chain.py tools/definitions/wa_dl.yaml --force\n"
            "  python3 tools/gen_chain.py --list\n"
        ),
    )
    parser.add_argument(
        "definition", nargs="?",
        help="Path to a YAML chain definition file",
    )
    parser.add_argument(
        "--list", action="store_true",
        help="List all engines currently configured in Kapish_debug.cfg",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print what would be generated/changed without writing any files",
    )
    parser.add_argument(
        "--force", action="store_true",
        help="Overwrite existing Lua files (default: skip if they already exist)",
    )
    parser.add_argument(
        "--config-dir", metavar="PATH",
        help=f"Override the configurations/ directory (default: {CONFIG_DIR})",
    )

    args = parser.parse_args()

    config_dir = Path(args.config_dir) if args.config_dir else CONFIG_DIR

    if args.list:
        cmd_list(config_dir)
    elif args.definition:
        cmd_generate(args)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
